import { dailyEditions } from './content/daily-editions.js';

const w = (id, type, title, author, life, year, minutes, category, culture, century, intro, source, sourceUrl, text, tags, rationale) => ({
  id, type, title, author: { name: author, lifespan: life, culture }, year, minutes: ({s7:20,p7:2,e7:4}[id] ?? minutes), category, century,
  intro, source: id==='e4'?'John Muir Writings':source, sourceUrl: id==='e4'?'https://www.yosemite.ca.us/john_muir_writings/our_national_parks/chapter_10.html':sourceUrl.replace("/wiki/Essays_(Bacon)/Of_Studies", "/wiki/The_Essays_of_Francis_Bacon/L_Of_Studies"), copyright: "Public domain", text, tags, difficulty: "Moderate", rationale
});

const archiveEditions = [
  {
    id: "2026-09-21", number: 7, date: "2026-09-21", theme: "Attention and the Unknown",
    curatorNote: "Tonight moves from cosmic unease to minute observation, then asks what education is really for.",
    works: [
      w("s7","story","The Star","H. G. Wells","1866–1946",1897,9,"Science fiction","British","19th century","A catastrophe seen from many human scales—one of Wells’s most restrained and haunting thought experiments.","Project Gutenberg","https://www.gutenberg.org/ebooks/27365",`It was on the first day of the new year that the announcement was made, almost simultaneously from three observatories, that the motion of the planet Neptune, the outermost of all the planets that wheel about the sun, had become very erratic. Ogilvy had already called attention to a suspected retardation in its velocity in December. Such a piece of news was scarcely calculated to interest a world the greater portion of whose inhabitants were unaware of the existence of the planet Neptune, nor outside the astronomical profession did the subsequent discovery of a faint remote speck of light in the region of the perturbed planet cause any very great excitement.\n\nScientific people, however, found the intelligence remarkable enough, even before it became known that the new body was rapidly growing larger and brighter, and that its motion was quite different from the orderly progress of the planets.`,["astronomy","catastrophe","humanity"],"Science fiction has been scarce in the recent sequence; this introduces a British fin-de-siècle voice and a planetary perspective."),
      w("p7","poem","To Autumn","John Keats","1795–1821",1820,3,"Ode","British","19th century","Keats’s last great ode notices ripeness without denying decline—a fitting poem for the autumn equinox.","Poetry Foundation","https://www.poetryfoundation.org/poems/44484/to-autumn",`Season of mists and mellow fruitfulness,\nClose bosom-friend of the maturing sun;\nConspiring with him how to load and bless\nWith fruit the vines that round the thatch-eves run;\nTo bend with apples the moss’d cottage-trees,\nAnd fill all fruit with ripeness to the core;\nTo swell the gourd, and plump the hazel shells\nWith a sweet kernel; to set budding more,\nAnd still more, later flowers for the bees,\nUntil they think warm days will never cease,\nFor Summer has o’er-brimm’d their clammy cells.`,["nature","seasons","beauty"],"A seasonal anchor and a study in sustained attention; Romantic poetry has not appeared in six editions."),
      w("e7","essay","Of Studies","Francis Bacon","1561–1626",1625,5,"Philosophy of education","British","17th century","A compact, bracing argument about what reading is—and is not—for. Bacon rewards disagreement as much as assent.","Wikisource","https://en.wikisource.org/wiki/Essays_(Bacon)/Of_Studies",`Studies serve for delight, for ornament, and for ability. Their chief use for delight is in privateness and retiring; for ornament, is in discourse; and for ability, is in the judgment and disposition of business. For expert men can execute, and perhaps judge of particulars, one by one; but the general counsels, and the plots and marshalling of affairs, come best from those that are learned.\n\nTo spend too much time in studies is sloth; to use them too much for ornament is affectation; to make judgment wholly by their rules is the humour of a scholar. They perfect nature, and are perfected by experience.`,["reading","education","judgment"],"The curriculum needs an early-modern essay and a direct reflection on reading itself."),
    ]
  },
  {
    id:"2026-09-20",number:6,date:"2026-09-20",theme:"Freedom and Measure",curatorNote:"Three writers test the boundaries between private conscience and public life.",works:[
      w("s6","story","A Horseman in the Sky","Ambrose Bierce","1842–c. 1914",1889,8,"War fiction","American","19th century","A Civil War story pared down to a single impossible choice.","Project Gutenberg","https://www.gutenberg.org/ebooks/13334",`One sunny afternoon in the autumn of the year 1861 a soldier lay in clump of laurel by the side of a road in western Virginia. He lay at full length upon his stomach, his feet resting upon the toes, his head upon the left forearm. His extended right hand loosely grasped his rifle. But for the somewhat methodical disposition of his limbs and a slight rhythmic movement of the cartridge-box at the back of his belt he might have been thought to be dead. He was asleep at his post of duty.`,["war","duty","conscience"],"A concise American story introduces moral ambiguity without overloading tonight’s reading time."),
      w("p6","poem","A Psalm of Life","Henry Wadsworth Longfellow","1807–1882",1838,3,"Lyric","American","19th century","Familiar in tone but stranger on inspection: a public poem arguing against passivity.","Poetry Foundation","https://www.poetryfoundation.org/poems/44644/a-psalm-of-life",`Tell me not, in mournful numbers,\nLife is but an empty dream!\nFor the soul is dead that slumbers,\nAnd things are not what they seem.\n\nLife is real! Life is earnest!\nAnd the grave is not its goal;\nDust thou art, to dust returnest,\nWas not spoken of the soul.`,["life","action","mortality"],"A historically popular public poem provides contrast with the story’s private moral crisis."),
      w("e6","essay","Civil Disobedience","Henry David Thoreau","1817–1862",1849,9,"Political philosophy","American","19th century","An uncompromising case for conscience over compliance, selected to be argued with rather than revered.","Project Gutenberg","https://www.gutenberg.org/ebooks/71",`I heartily accept the motto,—“That government is best which governs least”; and I should like to see it acted up to more rapidly and systematically. Carried out, it finally amounts to this, which also I believe,—“That government is best which governs not at all”; and when men are prepared for it, that will be the kind of government which they will have. Government is at best but an expedient; but most governments are usually, and all governments are sometimes, inexpedient.`,["politics","conscience","government"],"Political philosophy is underrepresented; this canonical position creates room for later opposing views."),
    ]
  },
  {
    id:"2026-09-19",number:5,date:"2026-09-19",theme:"Voice and Belonging",curatorNote:"A night about who is heard, who is at home, and who gets to define either condition.",works:[
      w("s5","story","The Story of an Hour","Kate Chopin","1850–1904",1894,6,"Realism","American","19th century","A famously compressed story whose emotional reversal still feels dangerous.","Wikisource","https://en.wikisource.org/wiki/The_Story_of_an_Hour",`Knowing that Mrs. Mallard was afflicted with a heart trouble, great care was taken to break to her as gently as possible the news of her husband's death.\n\nIt was her sister Josephine who told her, in broken sentences; veiled hints that revealed in half concealing. Her husband's friend Richards was there, too, near her.`,["marriage","freedom","women"],"Adds a woman realist and domestic interiority after several externally focused selections."),
      w("p5","poem","Sympathy","Paul Laurence Dunbar","1872–1906",1899,3,"Lyric","African American","19th century","The source of the phrase ‘the caged bird sings,’ in the complete poem that gave it force.","Poetry Foundation","https://www.poetryfoundation.org/poems/46459/sympathy-56d22658afbc0",`I know what the caged bird feels, alas!\nWhen the sun is bright on the upland slopes;\nWhen the wind stirs soft through the springing grass,\nAnd the river flows like a stream of glass;\nWhen the first bird sings and the first bud opes,\nAnd the faint perfume from its chalice steals—\nI know what the caged bird feels!`,["freedom","race","voice"],"Broadens the American tradition beyond its dominant white canon and connects form to constraint."),
      w("e5","essay","Strivings of the Negro People","W. E. B. Du Bois","1868–1963",1897,9,"Sociology","African American","19th century","Du Bois introduces double consciousness with a fusion of history, sociology, and lived experience.","The Atlantic","https://www.theatlantic.com/magazine/archive/1897/08/strivings-of-the-negro-people/305446/",`Between me and the other world there is ever an unasked question: unasked by some through feelings of delicacy; by others through the difficulty of rightly framing it. All, nevertheless, flutter round it. They approach me in a half-hesitant sort of way, eye me curiously or compassionately, and then, instead of saying directly, How does it feel to be a problem? they say, I know an excellent colored man in my town.`,["race","identity","sociology"],"Sociology and African American intellectual history are both gaps in the first week."),
    ]
  },
  {
    id:"2026-09-18",number:4,date:"2026-09-18",theme:"Nature’s Arguments",curatorNote:"Landscape becomes evidence: for kinship, for transience, and for preservation.",works:[
      w("s4","story","The White Heron","Sarah Orne Jewett","1849–1909",1886,9,"Regionalism","American","19th century","A child’s encounter with a rare bird becomes a subtle contest between knowledge and possession.","Project Gutenberg","https://www.gutenberg.org/ebooks/74943",`The woods were already filled with shadows one June evening, just before eight o’clock, though a bright sunset still glimmered faintly among the trunks of the trees. A little girl was driving home her cow, a plodding, dilatory, provoking creature in her behavior, but a valued companion for all that. They were going away from the western light, and striking deep into the woods, but their feet were familiar with the path, and it was no matter whether their eyes could see it or not.`,["nature","childhood","conservation"],"Nature writing needs a fictional voice; Jewett adds regional and ecological texture."),
      w("p4","poem","The River-Merchant’s Wife: A Letter","Li Bai","701–762",1915,3,"Classical poetry","Chinese","8th century","In Ezra Pound’s public-domain translation, absence is measured through moss, seasons, and distance.","Poetry Foundation","https://www.poetryfoundation.org/poems/47692/the-river-merchants-wife-a-letter",`While my hair was still cut straight across my forehead\nI played about the front gate, pulling flowers.\nYou came by on bamboo stilts, playing horse,\nYou walked about my seat, playing with blue plums.\nAnd we went on living in the village of Chōkan:\nTwo small people, without dislike or suspicion.`,["love","distance","translation"],"Introduces classical Chinese poetry and translation as part of the curriculum’s world-literature strand."),
      w("e4","essay","The American Forests","John Muir","1838–1914",1897,8,"Natural history","Scottish American","19th century","Muir’s ecstatic attention sharpens into an early conservation argument.","The Atlantic","https://www.theatlantic.com/magazine/archive/1897/08/the-american-forests/306673/",`The forests of America, however slighted by man, must have been a great delight to God; for they were the best he ever planted. The whole continent was a garden, and from the beginning it seemed to be favored above all the other wild parks and gardens of the globe.`,["ecology","forests","conservation"],"Natural history is underrepresented and offers a counterweight to abstract political essays."),
    ]
  },
  {
    id:"2026-09-17",number:3,date:"2026-09-17",theme:"Reason and Wonder",curatorNote:"The rational and marvelous are not opposites tonight; each corrects the other.",works:[
      w("s3","story","The Queen of Spades","Alexander Pushkin","1799–1837",1834,10,"Gothic fiction","Russian","19th century","A coolly told Russian tale of gambling, secrecy, and the mathematics of obsession.","Project Gutenberg","https://www.gutenberg.org/ebooks/23058",`There was a card party at the rooms of Narumov of the Horse Guards. The long winter night passed away imperceptibly, and it was five o'clock in the morning before the company sat down to supper. Those who had won ate with a good appetite; the others sat staring absently at their empty plates.`,["chance","obsession","Russia"],"Adds Russian literature and Gothic irony; Eastern Europe was absent from prior selections."),
      w("p3","poem","The Tyger","William Blake","1757–1827",1794,2,"Romantic poetry","British","18th century","A childlike meter carries an adult terror: what kind of maker creates destructive beauty.","Poetry Foundation","https://www.poetryfoundation.org/poems/43687/the-tyger",`Tyger Tyger, burning bright,\nIn the forests of the night;\nWhat immortal hand or eye,\nCould frame thy fearful symmetry?\n\nIn what distant deeps or skies.\nBurnt the fire of thine eyes?\nOn what wings dare he aspire?\nWhat the hand, dare seize the fire?`,["creation","beauty","religion"],"Romantic poetry supplies a compact metaphysical challenge alongside Pushkin’s calculated obsession."),
      w("e3","essay","On the Duty of Civil Disobedience — opening","Henry David Thoreau","1817–1862",1849,8,"Political philosophy","American","19th century","A deliberately provocative account of the individual’s obligations to an unjust state.","Project Gutenberg","https://www.gutenberg.org/ebooks/71",`I think that we should be men first, and subjects afterward. It is not desirable to cultivate a respect for the law, so much as for the right. The only obligation which I have a right to assume is to do at any time what I think right.`,["ethics","state","law"],"A difficult claim selected to create productive friction, not agreement."),
    ]
  },
  {
    id:"2026-09-16",number:2,date:"2026-09-16",theme:"Work and Dignity",curatorNote:"Tonight’s writers ask what labor costs—and what survives it.",works:[
      w("s2","story","The Overcoat","Nikolai Gogol","1809–1852",1842,11,"Satire","Ukrainian / Russian","19th century","Bureaucratic absurdity and human tenderness share the same threadbare coat.","Project Gutenberg","https://www.gutenberg.org/ebooks/36238",`In the department of—but it is better not to mention the department. For there is nothing more sensitive than a department, a regiment, a government office, in fact, any branch of public service. Nowadays every private individual considers the whole of society insulted in his person.`,["bureaucracy","poverty","dignity"],"Introduces satirical fiction from the Ukrainian-born Russian tradition and the theme of institutional life."),
      w("p2","poem","We Wear the Mask","Paul Laurence Dunbar","1872–1906",1896,2,"Lyric","African American","19th century","Dunbar’s formal control makes the social performance he describes feel more, not less, urgent.","Poetry Foundation","https://www.poetryfoundation.org/poems/44203/we-wear-the-mask",`We wear the mask that grins and lies,\nIt hides our cheeks and shades our eyes,—\nThis debt we pay to human guile;\nWith torn and bleeding hearts we smile,\nAnd mouth with myriad subtleties.`,["identity","race","performance"],"Adds an African American voice and complicates tonight’s theme of public roles."),
      w("e2","essay","A Piece of Chalk","G. K. Chesterton","1874–1936",1905,7,"Personal essay","British","20th century","An ordinary drawing expedition becomes a defense of limits, materials, and the color white.","Project Gutenberg","https://www.gutenberg.org/ebooks/8092",`I remember one splendid morning, all blue and silver, in the summer holidays when I reluctantly tore myself away from the task of doing nothing in particular, and put on a hat of some sort and picked up a walking-stick, and put six very bright-coloured chalks in my pocket.`,["art","attention","ordinary life"],"A lighter personal essay balances two heavier works and introduces visual art as a subject."),
    ]
  },
  {
    id:"2026-09-15",number:1,date:"2026-09-15",theme:"Beginnings",curatorNote:"The first edition begins with three acts of looking: at a city, a road, and the limits of knowledge.",works:[
      w("s1","story","An Occurrence at Owl Creek Bridge","Ambrose Bierce","1842–c. 1914",1890,10,"Psychological fiction","American","19th century","A formally daring story about time, perception, and the mind’s last refuge.","Project Gutenberg","https://www.gutenberg.org/ebooks/13334",`A man stood upon a railroad bridge in northern Alabama, looking down into the swift water twenty feet below. The man's hands were behind his back, the wrists bound with a cord. A rope closely encircled his neck. It was attached to a stout cross-timber above his head and the slack fell to the level of his knees.`,["time","war","perception"],"A gripping, formally inventive entry point whose brevity leaves room for reflection."),
      w("p1","poem","The Road Not Taken","Robert Frost","1874–1963",1915,3,"Modern poetry","American","20th century","Read past its reputation and the poem becomes less a hymn to independence than a puzzle about the stories we tell ourselves.","Poetry Foundation","https://www.poetryfoundation.org/poems/44272/the-road-not-taken",`Two roads diverged in a yellow wood,\nAnd sorry I could not travel both\nAnd be one traveler, long I stood\nAnd looked down one as far as I could\nTo where it bent in the undergrowth;`,["choice","memory","self-narration"],"A familiar poem chosen to model rereading against received wisdom."),
      w("e1","essay","On the Uncertainty of Our Judgment","Michel de Montaigne","1533–1592",1580,8,"Philosophy","French","16th century","Montaigne asks us to distrust tidy verdicts—including our own.","Project Gutenberg","https://www.gutenberg.org/ebooks/3600",`It is not, perhaps, without reason, that we attribute facility of belief and easiness of persuasion to simplicity and ignorance; for I have heard belief compared to the impression of a seal stamped upon the soul, and said that by how much softer and of less resistance the soul is, so much the more easy it is to impose anything upon it.`,["skepticism","judgment","knowledge"],"Begins the essay curriculum outside the Anglophone tradition and establishes intellectual humility as a guiding value."),
    ]
  }
];

export const editions = [...dailyEditions, ...archiveEditions.filter(edition=>!dailyEditions.some(daily=>daily.date===edition.date))].sort((a,b)=>b.date.localeCompare(a.date));
export const allWorks = editions.flatMap(e => e.works.map(work => ({...work, editionId:e.id, editionNumber:e.number, editionDate:e.date})));
export const todayEdition = editions[0];
